![Practicum AI Logo image](images/practicum_ai_logo.png)
***
(5 Minutes)

This exercise adapted from Baig et al. (2020) <i>The Deep Learning Workshop</i> from <a href="https://www.packtpub.com/product/the-deep-learning-workshop/9781839219856">Packt Publishers</a>.

#### Video Resources
- [Andrew Ng: Edge-Detection](https://www.youtube.com/watch?v=XuD4C8vJzEQ)

#### Exercise 3.01 (Teacher) - Page 113

<span style="color:steelblue">**(2)**</span>

In [2]:
import tensorflow as tf

***
![](images/02.1_convolution_image.jpg)

<span style="color:steelblue">**(3)**</span>

In [3]:
A = tf.Variable([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

<span style="color:steelblue">**(4)**</span>

In [4]:
B = tf.Variable([[1, 0, -1], [1, 0, -1], [1, 0, -1]])
B

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 1,  0, -1],
       [ 1,  0, -1],
       [ 1,  0, -1]], dtype=int32)>

<span style="color:steelblue">**(5)**</span>

In [5]:
mult_out = tf.math.multiply(A, B)
mult_out

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  0, -3],
       [ 4,  0, -6],
       [ 7,  0, -9]], dtype=int32)>

<span style="color:steelblue">**(6)**</span>

In [6]:
conv_out = tf.math.reduce_sum(mult_out)
conv_out

<tf.Tensor: shape=(), dtype=int32, numpy=-6>